services:
  postgres:
    image: postgres:13.0
    container_name: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
    networks:
      - hirewise_network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql


networks:
  hirewise_network:
    driver: bridge